/*Generated by WaveMaker Studio*/
package com.testdb_hsql.rolodex.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testdb_hsql.rolodex.Address;
import com.testdb_hsql.rolodex.Customer;
import com.testdb_hsql.rolodex.Store;

/**
 * Service object for domain model class {@link Address}.
 */
public interface AddressService {

    /**
     * Creates a new Address. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Address if any.
     *
     * @param addressInstance Details of the Address to be created; value cannot be null.
     * @return The newly created Address.
     */
	Address create(Address addressInstance);


	/**
	 * Returns Address by given id if exists.
	 *
	 * @param addressIdInstance The id of the Address to get; value cannot be null.
	 * @return Address associated with the given addressIdInstance.
     * @throws EntityNotFoundException If no Address is found.
	 */
	Address getById(Integer addressIdInstance) throws EntityNotFoundException;

    /**
	 * Find and return the Address by given id if exists, returns null otherwise.
	 *
	 * @param addressIdInstance The id of the Address to get; value cannot be null.
	 * @return Address associated with the given addressIdInstance.
	 */
	Address findById(Integer addressIdInstance);


	/**
	 * Updates the details of an existing Address. It replaces all fields of the existing Address with the given addressInstance.
	 *
     * This method overrides the input field values using Server side or database managed properties defined on Address if any.
     *
	 * @param addressInstance The details of the Address to be updated; value cannot be null.
	 * @return The updated Address.
	 * @throws EntityNotFoundException if no Address is found with given input.
	 */
	Address update(Address addressInstance) throws EntityNotFoundException;

    /**
	 * Deletes an existing Address with the given id.
	 *
	 * @param addressIdInstance The id of the Address to be deleted; value cannot be null.
	 * @return The deleted Address.
	 * @throws EntityNotFoundException if no Address found with the given id.
	 */
	Address delete(Integer addressIdInstance) throws EntityNotFoundException;

	/**
	 * Find all Addresses matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
	 *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
	 *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Addresses.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
	 */
    @Deprecated
	Page<Address> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Find all Addresses matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Addresses.
     *
     * @see Pageable
     * @see Page
	 */
    Page<Address> findAll(String query, Pageable pageable);

    /**
	 * Exports all Addresses matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
	 */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the Addresses in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
	 * @return The count of the Address.
	 */
	long count(String query);

    /*
     * Returns the associated customers for given Address id.
     *
     * @param addressId value of addressId; value cannot be null
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of associated Customer instances.
     *
     * @see Pageable
     * @see Page
     */
    Page<Customer> findAssociatedCustomers(Integer addressId, Pageable pageable);

    /*
     * Returns the associated stores for given Address id.
     *
     * @param addressId value of addressId; value cannot be null
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of associated Store instances.
     *
     * @see Pageable
     * @see Page
     */
    Page<Store> findAssociatedStores(Integer addressId, Pageable pageable);

}

