/*Generated by WaveMaker Studio*/
package com.testdb_hsql.rolodex.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testdb_hsql.rolodex.Address;
import com.testdb_hsql.rolodex.City;

/**
 * Service object for domain model class {@link City}.
 */
public interface CityService {

    /**
     * Creates a new City. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on City if any.
     *
     * @param cityInstance Details of the City to be created; value cannot be null.
     * @return The newly created City.
     */
	City create(City cityInstance);


	/**
	 * Returns City by given id if exists.
	 *
	 * @param cityIdInstance The id of the City to get; value cannot be null.
	 * @return City associated with the given cityIdInstance.
     * @throws EntityNotFoundException If no City is found.
	 */
	City getById(Integer cityIdInstance) throws EntityNotFoundException;

    /**
	 * Find and return the City by given id if exists, returns null otherwise.
	 *
	 * @param cityIdInstance The id of the City to get; value cannot be null.
	 * @return City associated with the given cityIdInstance.
	 */
	City findById(Integer cityIdInstance);


	/**
	 * Updates the details of an existing City. It replaces all fields of the existing City with the given cityInstance.
	 *
     * This method overrides the input field values using Server side or database managed properties defined on City if any.
     *
	 * @param cityInstance The details of the City to be updated; value cannot be null.
	 * @return The updated City.
	 * @throws EntityNotFoundException if no City is found with given input.
	 */
	City update(City cityInstance) throws EntityNotFoundException;

    /**
	 * Deletes an existing City with the given id.
	 *
	 * @param cityIdInstance The id of the City to be deleted; value cannot be null.
	 * @return The deleted City.
	 * @throws EntityNotFoundException if no City found with the given id.
	 */
	City delete(Integer cityIdInstance) throws EntityNotFoundException;

	/**
	 * Find all Cities matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
	 *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
	 *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Cities.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
	 */
    @Deprecated
	Page<City> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Find all Cities matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Cities.
     *
     * @see Pageable
     * @see Page
	 */
    Page<City> findAll(String query, Pageable pageable);

    /**
	 * Exports all Cities matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
	 */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the Cities in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
	 * @return The count of the City.
	 */
	long count(String query);

    /*
     * Returns the associated addresses for given City id.
     *
     * @param cityId value of cityId; value cannot be null
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of associated Address instances.
     *
     * @see Pageable
     * @see Page
     */
    Page<Address> findAssociatedAddresses(Integer cityId, Pageable pageable);

}

