/*Generated by WaveMaker Studio*/
package com.testdb_hsql.rolodex.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testdb_hsql.rolodex.FilmActor;
import com.testdb_hsql.rolodex.FilmActorId;

/**
 * Service object for domain model class {@link FilmActor}.
 */
public interface FilmActorService {

    /**
     * Creates a new FilmActor. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on FilmActor if any.
     *
     * @param filmActor Details of the FilmActor to be created; value cannot be null.
     * @return The newly created FilmActor.
     */
	FilmActor create(FilmActor filmActor);


	/**
	 * Returns FilmActor by given id if exists.
	 *
	 * @param filmactorId The id of the FilmActor to get; value cannot be null.
	 * @return FilmActor associated with the given filmactorId.
     * @throws EntityNotFoundException If no FilmActor is found.
	 */
	FilmActor getById(FilmActorId filmactorId) throws EntityNotFoundException;

    /**
	 * Find and return the FilmActor by given id if exists, returns null otherwise.
	 *
	 * @param filmactorId The id of the FilmActor to get; value cannot be null.
	 * @return FilmActor associated with the given filmactorId.
	 */
	FilmActor findById(FilmActorId filmactorId);


	/**
	 * Updates the details of an existing FilmActor. It replaces all fields of the existing FilmActor with the given filmActor.
	 *
     * This method overrides the input field values using Server side or database managed properties defined on FilmActor if any.
     *
	 * @param filmActor The details of the FilmActor to be updated; value cannot be null.
	 * @return The updated FilmActor.
	 * @throws EntityNotFoundException if no FilmActor is found with given input.
	 */
	FilmActor update(FilmActor filmActor) throws EntityNotFoundException;

    /**
	 * Deletes an existing FilmActor with the given id.
	 *
	 * @param filmactorId The id of the FilmActor to be deleted; value cannot be null.
	 * @return The deleted FilmActor.
	 * @throws EntityNotFoundException if no FilmActor found with the given id.
	 */
	FilmActor delete(FilmActorId filmactorId) throws EntityNotFoundException;

	/**
	 * Find all FilmActors matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
	 *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
	 *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching FilmActors.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
	 */
    @Deprecated
	Page<FilmActor> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Find all FilmActors matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching FilmActors.
     *
     * @see Pageable
     * @see Page
	 */
    Page<FilmActor> findAll(String query, Pageable pageable);

    /**
	 * Exports all FilmActors matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
	 */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the FilmActors in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
	 * @return The count of the FilmActor.
	 */
	long count(String query);


}

