/*Generated by WaveMaker Studio*/
package com.testdb_hsql.rolodex.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testdb_hsql.rolodex.Inventory;

/**
 * Service object for domain model class {@link Inventory}.
 */
public interface InventoryService {

    /**
     * Creates a new Inventory. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Inventory if any.
     *
     * @param inventory Details of the Inventory to be created; value cannot be null.
     * @return The newly created Inventory.
     */
	Inventory create(Inventory inventory);


	/**
	 * Returns Inventory by given id if exists.
	 *
	 * @param inventoryIdInstance The id of the Inventory to get; value cannot be null.
	 * @return Inventory associated with the given inventoryIdInstance.
     * @throws EntityNotFoundException If no Inventory is found.
	 */
	Inventory getById(Integer inventoryIdInstance) throws EntityNotFoundException;

    /**
	 * Find and return the Inventory by given id if exists, returns null otherwise.
	 *
	 * @param inventoryIdInstance The id of the Inventory to get; value cannot be null.
	 * @return Inventory associated with the given inventoryIdInstance.
	 */
	Inventory findById(Integer inventoryIdInstance);


	/**
	 * Updates the details of an existing Inventory. It replaces all fields of the existing Inventory with the given inventory.
	 *
     * This method overrides the input field values using Server side or database managed properties defined on Inventory if any.
     *
	 * @param inventory The details of the Inventory to be updated; value cannot be null.
	 * @return The updated Inventory.
	 * @throws EntityNotFoundException if no Inventory is found with given input.
	 */
	Inventory update(Inventory inventory) throws EntityNotFoundException;

    /**
	 * Deletes an existing Inventory with the given id.
	 *
	 * @param inventoryIdInstance The id of the Inventory to be deleted; value cannot be null.
	 * @return The deleted Inventory.
	 * @throws EntityNotFoundException if no Inventory found with the given id.
	 */
	Inventory delete(Integer inventoryIdInstance) throws EntityNotFoundException;

	/**
	 * Find all Inventories matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
	 *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
	 *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Inventories.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
	 */
    @Deprecated
	Page<Inventory> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Find all Inventories matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Inventories.
     *
     * @see Pageable
     * @see Page
	 */
    Page<Inventory> findAll(String query, Pageable pageable);

    /**
	 * Exports all Inventories matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
	 */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the Inventories in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
	 * @return The count of the Inventory.
	 */
	long count(String query);


}

