/*Generated by WaveMaker Studio*/
package com.testdb_hsql.rolodex;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

public class FilmActorId implements Serializable {

    private Integer actorId;
    private Integer filmId;

    public Integer getActorId() {
        return this.actorId;
    }

    public void setActorId(Integer actorId) {
        this.actorId = actorId;
    }

    public Integer getFilmId() {
        return this.filmId;
    }

    public void setFilmId(Integer filmId) {
        this.filmId = filmId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof FilmActor)) return false;
        final FilmActor filmActor = (FilmActor) o;
        return Objects.equals(getActorId(), filmActor.getActorId()) &&
                Objects.equals(getFilmId(), filmActor.getFilmId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getActorId(),
                getFilmId());
    }
}
